version: 2
updates:
  # Monitor Python dependencies in requirements.txt
  - package-ecosystem: "pip"
    directory: "/"              # location of requirements.txt
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Monitor Docker Compose files for new MongoDB images
  - package-ecosystem: "docker"
    directory: "/src"           # adjust if your docker-compose file is elsewhere
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2

  # Optionally monitor GitHub Actions for updates
  - package-ecosystem: "github-actions"
    directory: "/"              # root of your repo
    schedule:
      interval: "weekly"