version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC API
    env_file:
      - .env.qdrant
    environment:
      QDRANT__SERVICE__ENABLE_AUTH: "true"
      QDRANT__SERVICE__ENABLE_CORS: "true"
      QDRANT__CLUSTER__ENABLED: "false"
      QDRANT__STORAGE__PATH: /qdrant/storage
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
