name: Python Storage Loaders CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        env:   # 👈 setup mongo
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGODB_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
          MONGO_INITDB_DATABASE: ${{ secrets.MONGODB_DATABASE }}  
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand(\"ping\").ok'" 
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:  # 👈 Environment variables, some from secrets
      MONGODB_HOST: localhost
      MONGODB_PORT: 27017
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pymongo

      - name: Run tests
        run: pytest tests/storage/ -v