name: Python CI (SonarCloud & Coverage)

on:
  workflow_call:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download coverage report (extractors)
        uses: actions/download-artifact@v4
        with:
          name: extractors-coverage-report
        continue-on-error: true

      - name: Download coverage report (api)
        uses: actions/download-artifact@v4
        with:
          name: api-coverage-report
        continue-on-error: true

      - name: Download coverage report (storage)
        uses: actions/download-artifact@v4
        with:
          name: storage-coverage-report
        continue-on-error: true

      - name: Combine coverage reports
        run: |
          ls -l *.xml || true
          coverage combine || true
          coverage xml || true
        continue-on-error: true

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v5
        with:
          args: >
            -Dsonar.projectKey=${{ github.repository }}
            -Dsonar.organization=scott-london
            -Dsonar.projectKey=scott-london_SourceSherpa
            -Dsonar.python.version=3.12
            -Dsonar.python.coverage.reportPaths=coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
